### ISSUE TITLE
Related project: copee

### ISSUE THREAD

**Issue by styfle** [sindresorhus/copy-text-to-clipboard#18]
Hello Sindre,

I created [copee](https://copee.ceriously.com) in 2015 which is similar to this one.

The difference is copee includes two methods: `toClipboard` and `fromElement`.
It also has TypeScript declarations included for users who like types.

Should I add a link in the readme to https://github.com/styfle/copee or do you want to collaborate at all?

**Comment by sindresorhus** [comment]
I never saw `copee`. Had I seen it back when I made this module, I probably wouldn't have bothered making this. My goal then was just to implement the smallest and simplest possible module for copying. No sugar. Since `clipboard.js` was so bloated.

It doesn't really make sense to link to `copee` as it's so similar.
