### ISSUE TITLE
Unfair comparison with Clipboard.js

### ISSUE THREAD

**Issue by hugmanrique** [sindresorhus/copy-text-to-clipboard#2]
Clipboard.js allows to have DOM attributes to copy text and provides more advanced functionalities that this module lacks. As so, I feel like it's a bit unfair to compare its size with your repo as they don't provide the same functionalities.

**Comment by jamen** [comment]
But are those _features_ worth the extra `3.2kb` all the time?  Use the modules that suit your needs best whether that be through extra features or smaller bundle sizes.  But, I don't think presenting that comparison is unfair.

It doesn't offer as many features out-of-the-box, sure.  But, in an alternative perspective, it still offers _more features_ because it is easily composed with other tiny packages.  The other packages would possibly negate whatever features clipboard.js provides if you even need them, and if they don't then it is probably more interesting to discuss those specifics

**Comment by sindresorhus** [comment]
I link to `clipboard.js` so people can make their own assessment whether the larger size is worth the extra features. Ideally, `clipboard.js` would have been modular, so I wouldn't have needed to make this module in the first place.
